### model params
Model:
# for cifar10
  in_channels: 3
  out_channels: 3
# # for mnist
#   in_channels: 1
#   out_channels: 1

  model_channels: 128
  attention_resolutions: [2, ]
  num_res_blocks: 2
  dropout: 0.1
  channel_mult: [1, 2, 2, 2]
  conv_resample: True
  num_heads: 4

### dataset params
Dataset:
  # Deciding which dataset to use, must be one of {'mnist', 'cifar','celeba', 'butterflies' 'custom'}.
  dataset: "butterflies"
  # If mnist and cifar datasets, whether to use the training set.
  train: True
  # Folder of data sets. When `dataset = custom`, this parameter can be a list with different folders.
  # Then all images in the list with suffixes in `suffix` in the folder will be loaded.
  data_path: "./data"
  # If mnist and cifar datasets, whether to download it.
  download: False
  # If mnist dataset, image_size is [28, 28]. 
  # If cifar dataset, image_size is [32, 32].
  # If butterflies dataset, image_size is [128, 128]
  # If custom, specify as needed.
  image_size: [ 128, 128 ]

  # If custom dataset, what is the mode of the image. must be one of {'RGB', 'L', 'CMYK'}.
  mode: "RGB"
  # If custom dataset, decide what suffix to load for the image.
  suffix: ["png", "jpg"]

  # parameters for torch.utils.data.DataLoader
  batch_size: 16 #64
  shuffle: True
  drop_last: True
  pin_memory: True
  num_workers: 4

### trainer params
Trainer:
  # sample time steps
  T: 1000
  beta: [0.0001, 0.02]


### callback params
Callback:
  # The save path for checkpoint.
  # filepath: "./checkpoint/cifar10_2.pth"
  filepath: "./checkpoint/butterflies_250.pth"
  # Frequency of checkpoint saving.
  save_freq: 1

### train params
device: "cuda:0"
# device: "cpu"

### If continue training, epochs is the epochs you want to continue to train.
### For example, if you have already train 1000 epochs, then you want to train more 1000 epochs, that means you train 2000 epoches in total. 
### So you need to set the following epochs to 1000.
epochs: 250
# Whether to continue training, True or False
consume: False
# If continue training, which checkpoint to load
# consume_path: "./checkpoint/cifar10_2.pth"
consume_path: "./checkpoint/butterflies_250.pth"
### optimizer params
lr: 0.0002
